# Builds docker container to build Go app and package it with DEB.

FROM ubuntu:16.04

MAINTAINER "Nikolay Turpitko"

ARG golang_version
ARG glide_version

ENV container=docker \
    PATH=/usr/local/go/bin:/go/bin:$PATH \
    GOPATH=/go

RUN apt-get -q -y update; \
    apt-get -q -y upgrade; \
    apt-get -q -y install \
        make \
        devscripts \
        lintian \
        dh-make \
        dh-systemd \
        pandoc; \
    apt-get -q -y autoremove; \
    apt-get -q -y autoclean; \
    curl -sSL https://storage.googleapis.com/golang/go${golang_version}.linux-amd64.tar.gz | tar -xz -C /usr/local; \
    mkdir -p /go/src; \
    curl -sSL https://github.com/Masterminds/glide/releases/download/v${glide_version}/glide-v${glide_version}-linux-amd64.tar.gz \
    | tar -xz --strip=1 --no-same-owner --owner=root --group=root -C /usr/local/bin linux-amd64/glide

COPY Makefile /Makefile

ENTRYPOINT ["/usr/bin/make"]
